name: Main Workflow
on: [push]
run-name: NestJS pipeline workflow
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: yarn install --immutable
